name: reviewdog
on: [push, pull_request]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          locale: "US"
          level: "error"
      - name: Run perlcritic
        uses: reviewdog/action-perlcritic@fun
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: "error"
          perlcritic_flags: "--quiet --profile .perlcriticrc --verbose '%f:%l:%c:**%m**, near <code>%r</code>.<br>(Ref: [%p](https://metacpan.org/pod/Perl::Critic::Policy::%p))\n' ."
