name: reviewdog
on: [push, pull_request]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          locale: "US"
  perlcritic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run perlcritic
        uses: gugod/action-perlcritic@fun
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review

