name: reviewdog
on: [push, pull_request]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          locale: "US"
      - name: perlcritic
        uses: gugod/action-perlcritic@v1
        with:
          reporter: github-pr-review
